### ISSUE TITLE
Right clicking on the assembler causes a crash

### ISSUE THREAD

**Issue by Voxelstice** [MartinTheDragon/Nuclear-Tech-Mod-Remake#15]
**Describe the bug**
Title should be self-explanatory.

**To Reproduce**
1. Place an assembler
2. Right click on the assembler

**Expected behavior**
Assembler UI appearing upon right click.

**Software and mod environment info (please complete the following information):**
 - Mod Version: 0.0.14.0.
 - Other mods installed: [modlist.txt](https://github.com/MartinTheDragon/Nuclear-Tech-Mod-Remake/files/9454606/modlist.txt)
 - Forge version: 1.18.2-40.1.60

**Additional context**
what the hell is with the crash report
[crashreport.txt](https://github.com/MartinTheDragon/Nuclear-Tech-Mod-Remake/files/9454608/crashreport.txt)

**Comment by MartinTheDragon** [comment]
Hi!
This is a known issue in relation to some other mod. It should™ be fixed indev and will roll out with the next release.
Thanks for reporting.
