### ISSUE TITLE
Shredder Broken

### ISSUE THREAD

**Issue by PigOfBusiness** [MartinTheDragon/Nuclear-Tech-Mod-Remake#16]
### Issue description

If you put any item that has electricity like a battery or a electricity charged item from other mods it will create scrap indefinitely. Works with any mods and presumably anything that acts like a battery.
Edit: The shredder is just flat out broken. It works with everything.

### Steps to reproduce

Charge a shredder with any battery and put the shredder blades in to set it up
Put in a battery or anything like it
Thats it

### Forge version

Public Test Server

### Nuclear Tech version

0.0.15

### Other mods

Public Test Server

**Comment by MartinTheDragon** [comment]
Oh, I forgot to actually remove the item if it gets processed into scrap when I extracted the `BlockEntity` base classes.
Thanks for reporting!
