### ISSUE TITLE
The higher a radiation source is, the further the radiation will spread

### ISSUE THREAD

**Issue by JulekJulas** [MartinTheDragon/Nuclear-Tech-Mod-Remake#17]
**Is your feature request related to a problem? Please describe.**
Cuz wind you know 

**Describe the solution you'd like**
y=64 = *1, y=128*1.3 etc

**Describe alternatives you've considered**
None really

**Additional context**
It works the same in caves but lowered y=32 = *0.7

**Comment by MartinTheDragon** [comment]
I feel like there are too many cases such an implementation wouldn't cover properly. Besides, this would require 3D chunk radiation, which isn't ported yet, and 3D chunk radiation should properly spread the radiation anyway.

**Comment by username90001** [comment]
> Contributor

its not related with radiation source radiation will spread better at higher  altitudes due to lower atmosphere pressure but on ground it will become lower and range of radiation will become lower too that can work only if radiation source is dust in atmosphere
