### ISSUE TITLE
The texture are messed up from the new update.

### ISSUE THREAD

**Issue by Aerhtjiz** [MartinTheDragon/Nuclear-Tech-Mod-Remake#24]
### Issue description

The texture for rain, smoke, and i guess every other particles are glitched out. There textures are very weird. 
https://user-images.githubusercontent.com/117865514/207460830-802a2c0f-a83c-44db-a447-a887675cb264.png

### Forge version

40.1.86

### Nuclear Tech version

Manually compiled

**Comment by MartinTheDragon** [comment]
Rain looks normal for me, are you sure you don't have any other mods installed?
Does it occur immediately or after performing a certain action?

**Comment by Aerhtjiz** [comment]
> Rain looks normal for me, are you sure you don't have any other mods installed? Does it occur immediately or after performing a certain action?

Ok so i figured it out, it is a problem with rubidium and or oculus mod. The only reason I use it is because optifine crashes with it.
