### ISSUE TITLE
you cant mine blocks

### ISSUE THREAD

**Issue by ZifyyCZ** [MartinTheDragon/Nuclear-Tech-Mod-Remake#26]
### Issue description

you cant mine ores, blocks, machines with a pickaxe

(you gotta make a pickaxe.json file in "...resources/data/minecraft/tags/" with all of the modded blocks listed there)

i expect this to be "fixed" sometime in the future and not now as it's the survival part, and im pretty sure as of now you're just trying to make everything work

### Steps to reproduce

1. get in a cave
2. find an ore
3. pull up your pickaxe
4. realise you cant mine it (it's like mining it with your hand)

### Forge version

40.1.86

### Nuclear Tech version

Manually compiled

**Comment by MartinTheDragon** [comment]
Hi!
I cannot confirm this to be the case, everything works as it should and the [`pickaxe.json` exists](https://github.com/MartinTheDragon/Nuclear-Tech-Mod-Remake/blob/0e598edc2b9c2271bec830c1132f19966f734c3c/src/datagen/generated/resources/data/minecraft/tags/blocks/mineable/pickaxe.json), as well as its [data generator](https://github.com/MartinTheDragon/Nuclear-Tech-Mod-Remake/blob/1.18/src/datagen/main/kotlin/at/martinthedragon/nucleartech/datagen/HarvestabilityProvider.kt).
Should there be any specific block that you can't harvest properly, please let me know. Maybe I forgot something, but I went through the entire block list once, and always add blocks to the proper tags when I add them.
Have fun playing!

**Comment by ZifyyCZ** [comment]
Well i dont see it in https://github.com/MartinTheDragon/Nuclear-Tech-Mod-Remake/tree/1.18/src/main/resources and the last release was a month ago (which is the one i am currently using)

**Comment by ZifyyCZ** [comment]
oops i uh clicked something and closed it by accident

**Comment by MartinTheDragon** [comment]
> Well i dont see it in https://github.com/MartinTheDragon/Nuclear-Tech-Mod-Remake/tree/1.18/src/main/resources and the last release was a month ago (which is the one i am currently using)

Because the file is generated. It's not under `src/main`, it's under `src/datagen/generated`. I separated data generation from normal code to avoid shipping the mod with unnecessary code, because the data generators make up a substantial part.
And I tested it with that release, everything works. Send me a video or something or actually provide a list of other mods if you're not only playing with NTM.

**Comment by ZifyyCZ** [comment]
ohhh.. ok, i'm gonna try it with just nuclear tech mod first and then if that won't work too i'm gonna send a video

**Comment by ZifyyCZ** [comment]
welp, it's again because of my mod, it works fine without my mod, i probably messed something up, i'll try to fix it
(thanks for the quick responses tho)

**Comment by MartinTheDragon** [comment]
Have you tried other blocks like vanilla ones too? Maybe your tag definition is replacing the vanilla one. Make sure to set `"replace": false` in the tag file.

**Comment by ZifyyCZ** [comment]
thats really weird.. i already have it set to false, i even put everything from NTM's pickaxe.json to my mod's pickaxe.json and it still doesnt work

**Comment by MartinTheDragon** [comment]
The path **must** be exactly `data/minecraft/tags/blocks/mineable/pickaxe.json`. Make sure it really is there. It can't be in your own mod id, it has to be under `minecraft`.

**Comment by MartinTheDragon** [comment]
Other than that I can't really tell you what's going on. Your mod isn't open source either, so I can only guess.

**Comment by ZifyyCZ** [comment]
there was an invalid block the entire time (`nucleartech:centrifuge`), the file just didn't load, works now just fine even with my mod

**Comment by MartinTheDragon** [comment]
The centrifuge isn't released yet, and if you indeed actually compiled your own version, it should work nevertheless. It is impossible for the data generator to generate an invalid file, and I didn't mix anything up with the commits. Are you sure that was the issue?

**Comment by MartinTheDragon** [comment]
> thats really weird.. i already have it set to false, i even put everything from NTM's pickaxe.json to my mod's pickaxe.json and it still doesnt work

Oh it's because you copied it. Then what was the issue initially? Why even copy stuff in the first place? Are you putting NTM into Warfront?

**Comment by ZifyyCZ** [comment]
> > thats really weird.. i already have it set to false, i even put everything from NTM's pickaxe.json to my mod's pickaxe.json and it still doesnt work
> 
> Oh it's because you copied it. Then what was the issue initially? Why even copy stuff in the first place? Are you putting NTM into Warfront?

in the "Minecraft game output" aka console it said something like "could not load minecraft:mineable/pickaxe.json because nucleartech:centrifuge is there", works totally fine without my mod, but with my mod i have to put everything from NTM's pickaxe.json to my mod's pickaxe.json and just remove the centrifuge entry. 

yea i put NTM in Warfront, i am quite sure it's because i have my own pickaxe.json file.
(i can put your mod into my mod as a something of a dependency without putting it in a modpack, right..? from what i could tell the "GNU General Public License v3.0" license allows that and i can put the NTM jar file in the warfront's META-INF/libs directory right? probably should've asked you if i can do that beforehand tho..)

**Comment by MartinTheDragon** [comment]
Please read the [GNU GPLv3 license](https://spdx.org/licenses/GPL-3.0-or-later.html).
You can find a short summary [here](https://choosealicense.com/licenses/gpl-3.0/), but that doesn't replace reading the full license.
You may not distribute NTM without disclosing source and source code, and any larger or derived works (in this case the Warfront mod if you include it like that) must also be licensed under GPLv3.
And even if you were to follow all that, including mods like that is just really bad practice. Please don't do that and make a proper mod pack instead.
Comply with the license or measures will be taken.

> To protect your rights, we need to prevent others from denying you
these rights or asking you to surrender the rights.  Therefore, you have
certain responsibilities if you distribute copies of the software, or if
you modify it: responsibilities to respect the freedom of others.

> For example, if you distribute copies of such a program, whether
gratis or for a fee, you must pass on to the recipients the same
freedoms that you received.  You must make sure that they, too, receive
or can get the source code.  And you must show them these terms so they
know their rights.

**Comment by ZifyyCZ** [comment]
Well my source code is disclosed, is it not? And I kinda need NTM to be inside of Warfront for items to be craftable. Is there any way to somehow include NTM without it actually being in the Warfront.jar file without making a modpack? Or would I just have to tell people to install NTM in order to be able to craft items? I can understand and remove everything about NTM from Warfront if you won't allow me to include the mod in my mod, but I don't want to have items uncraftable unless people also install NTM. I'm fine with NTM being in a modpack as I am currently preparing a modpack for a Minecraft server, but I also want people who just download Warfront from Curseforge to be able to craft items. Yet again, if the only way to "include" NTM would be by telling people to download NTM too in order to craft items, I understand.

**Comment by MartinTheDragon** [comment]
I don't see any source neither on CurseForge nor on your GitHub profile. You also don't mention use of NTM anywhere, unless that's not released yet.
You can add recipes through the mod pack itself using data packs. If there are crafting recipes that use both NTM-specific and Warfront-specific items (no tagging), then you can do something like the following in your `mods.toml`:
```toml
[[dependencies.warfront]] # or whatever your mod id is
  modId="nucleartech"
  mandatory=true
  versionRange="[0.0.18.0,)"
  ordering="NONE"
  side="BOTH"
```

This will make sure people load Warfront with NTM.
If you need access to internal NTM code, you have to setup a Gradle dependency for it using `fg.deobf("at.martinthedragon:nucleartech:0.0.18.0")` or something like that while also setting up a local repository where Gradle can source the mod jar from, as I haven't published the mod on any Maven repositories yet. I haven't actually tried that with NTM yet, so you might have to experiment a bit.

**Comment by ZifyyCZ** [comment]
Well that's everything (recipes, mods.toml, build.properties `implementation fg.deobf(src/meta-inf/libs/ntm.jar)`, ) what I've done so far (+ putting NTM to META-INF/libs)

and yeah I'm not mentioning it since it's not released yet.

so if i understood correctly, in order to compy with the license I just have to remove NTM from META-INF/libs and tell people to download it seperately? or i can have it there but just set the license to GPLv3 and credit/mention you/your work? I'm kinda a bit lost right now...

**Comment by MartinTheDragon** [comment]
You just have to do what the license says. Everything should still work if you move NTM into some other folder outside of source (also I'm not sure if META-INF should even be used like that).
And yeah either you do it properly, then everything will be fine on its own if you still mention NTM, or you continue doing your hacky way, but release the source code and license it under GPLv3 as well (while also mentioning that your work is derived from NTM and stating every change made, because if you include it in an inseparable way like that, it doesn't count as library usage).

**Comment by ZifyyCZ** [comment]
Ohhh.. I get it now, this whole time I thought "disclose" meant to hide something, and not show it. Ok I will see what I can do. Thanks! So either I just remove NTM.jar from the META-INF/libraries (and if I want to force people to have it I will keep it in mods.toml) folder and tell people to download it seperately, or I release the source code, keep NTM in META-INF, change license to GPLv3, mention NTM, and mention any changes I make to NTM. Correct me if I misunderstood it, but I hope I did not.

**Comment by MartinTheDragon** [comment]
Basically yes, although make sure to read through the license and follow it. What I said doesn't apply from a legal standpoint. Either way, I definitely recommend the first option. That's how it should be done and that's how it works well without issues like #25 or #26 happening.

**Comment by ZifyyCZ** [comment]
Hmm, thanks! Great to know.
