### ISSUE TITLE
Multiblock machines cause a lot of performance drop if you put too many of them.

### ISSUE THREAD

**Issue by Ethanedc** [MartinTheDragon/Nuclear-Tech-Mod-Remake#29]
### Issue description

Why happen this?

### Forge version

40.2.0

### Nuclear Tech version

0.0.18

**Comment by MartinTheDragon** [comment]
Because Minecraft's rendering engine is archaic and really poorly optimized, especially for block entity rendering, which all of the multi block machines use. I have plans for implementing GPU instancing, which should hopefully solve that issue somewhat.

**Comment by Ethanedc** [comment]
ok thanks :)
P.D: i like the camera shake of the nuclear bombs.
