### ISSUE TITLE
RBMK control station is fully black on linux

### ISSUE THREAD

**Issue by likeproblem** [MartinTheDragon/Nuclear-Tech-Mod-Remake#36]
### Issue description

I use prism launcher on my linux. When I place RBMK control, there are no textures and fully black. I tested same modpack on my Windows PC, everything works well.

### Steps to reproduce

1.Use Arch Linux
2.Use Prism Launcher
3.Create any world
4.Place RBMK control station

### Forge version

1.18.2 40.2.0

### Nuclear Tech version

0.0.19

### Other mods

![image](https://user-images.githubusercontent.com/75926463/217401826-cc1fab5c-c75b-4150-af4d-e183b93697c9.png)

### (Crash) Log

No errors

**Comment by MartinTheDragon** [comment]
Hi there!
That sounds like a graphics driver issue. Please check those and update if needed.

(I also run an Arch-based OS)
![image](https://user-images.githubusercontent.com/50992877/217402187-7b9dc941-608f-4e17-9e61-ae2dd11f58d0.png)

**Comment by likeproblem** [comment]
> Hi there! That sounds like a graphics driver issue. Please check those and update if needed.>

I wanna add, Im using Steam Deck, and it has very strange videocard, it is AMD custom one, and full operating system is SteamOS. All is updated, Im not sure how to update vedeodrivers on SteamOS, I will answer when I will get my Steam Deck in minutes(I placed it on my shelf, can't get it)

**Comment by MartinTheDragon** [comment]
I actually remember someone else having that issue as well on Windows, it was for smooth shading in specific, which the RBMK Console uses (back then it was the Assembler but that no longer uses smooth shading). The person couldn't really understand that, and we never figured out if it actually was a graphics driver issue or not.

**Comment by MartinTheDragon** [comment]
> I wanna add, Im using Steam Deck, and it has very strange videocard, it is AMD custom one, and full operating system is SteamOS. All is updated, Im not sure how to update vedeodrivers on SteamOS, I will answer when I will get my Steam Deck in minutes(I placed it on my shelf, can't get it)

Ah okay, I'm not sure then.

**Comment by MartinTheDragon** [comment]
I have looked around a bit and the only other usage of smooth cutout shading in Minecraft are the Ender Dragon's crystal beams. Can you check if those render pitch black as well?

**Comment by likeproblem** [comment]
> I have looked around a bit and the only other usage of smooth cutout shading in Minecraft are the Ender Dragon's crystal beams. Can you check if those render pitch black as well?

Did you mean look at Ender's crystals?

**Comment by likeproblem** [comment]
![image](https://user-images.githubusercontent.com/75926463/221726800-7ca76e33-cf43-4f90-95de-212fd779e3e3.png)

Look like I got it. Everything is normal, except for black lines between crystal and dragon. It more look like as linux or prism launcher problem

**Comment by MartinTheDragon** [comment]
Ah okay, that must be an issue with AMD graphics then, which I can't really fix.
Thanks anyway!

**Comment by MartinTheDragon** [comment]
Actually, maybe I could make an option to disable smooth shading in the client config.

**Comment by MartinTheDragon** [comment]
I should've tried this earlier, but apparently there's no difference between `entityCutout` and `entitySmoothCutout` for the RBMK Console, at least as far as I can tell. I don't know where vanilla Minecraft messed up here, but I think we can just fix this by switching back to `entityCutout`.
Again, thanks for reporting!
