### ISSUE TITLE
1.18.2 not working on Server

### ISSUE THREAD

**Issue by LoadingBatu** [MartinTheDragon/Nuclear-Tech-Mod-Remake#37]
### Issue description

I wanted to use the mod on my server and when i start my server with the mod and then it crashes

(I dont have Optifine Installed on my Server)

### Steps to reproduce

1. Put Nuclear tech in my server
2. Start server
3. See error

### Forge version

I Think its 1.18.2 40.2.1

### Nuclear Tech version

0.0.19

### Other mods

The Mods (2 Screenshots)
![Screenshot (117)](https://user-images.githubusercontent.com/124925479/217923270-95b54897-cfaa-443a-8eac-cd1edc4868e6.png)
![Screenshot (118)](https://user-images.githubusercontent.com/124925479/217923297-68baa627-4a13-45d2-b912-bf2304399fa7.png)

### (Crash) Log

The Password is: GetGnomed                                                                                                                                                               https://pastebin.com/PFmWQXaX

**Comment by LoadingBatu** [comment]
https://pastebin.com/PFmWQXaX

**Comment by MartinTheDragon** [comment]
Hello!
Looks like somehow some part of LWJGL is missing? I'm relying on a utility function it has to get the `Unsafe` instance (because I was a bit lazy), which requires a bit of trickery. I guess I'll have to make my own implementation, I'll fix it right now.

**Comment by LoadingBatu** [comment]
ok, Could you notice me when its fixed

**Comment by MartinTheDragon** [comment]
There, [made a hotfix](https://github.com/MartinTheDragon/Nuclear-Tech-Mod-Remake/releases/tag/v1.18.2-0.0.19.1).

**Comment by LoadingBatu** [comment]
Thanks
