### ISSUE TITLE
NTM crash my forge server while stable works on forge client

### ISSUE THREAD

**Issue by likeproblem** [MartinTheDragon/Nuclear-Tech-Mod-Remake#39]
### Issue description

I have same(copy paste) mods on client and server, but server always crash because of NTM

### Steps to reproduce

1.Use forge server
2.Launch server with same mods
3.Have great time with errors!

### Forge version

1.18.2 40.2.0

### Nuclear Tech version

0.0.19

### Other mods

![image](https://user-images.githubusercontent.com/75926463/218231933-86c52f8f-18a1-40bc-935c-0e5939af02bd.png)
[crash-2023-02-10_17.27.49-fml.txt](https://github.com/MartinTheDragon/Nuclear-Tech-Mod-Remake/files/10712310/crash-2023-02-10_17.27.49-fml.txt)

### (Crash) Log

File above

**Comment by likeproblem** [comment]
If needed I can send zip with mods

**Comment by likeproblem** [comment]
One More: Mod crashes by itself, I tested only with NTM

**Comment by JulekJulas** [comment]
Could you send the error log of just the server and ntm?

**Comment by likeproblem** [comment]
>Could you send the error log of just the server and ntm?

[crash-2023-02-10_17.52.06-fml.txt](https://github.com/MartinTheDragon/Nuclear-Tech-Mod-Remake/files/10712349/crash-2023-02-10_17.52.06-fml.txt)

**Comment by JulekJulas** [comment]
Alright I have to go to sleep as it's 3:33 AM right now but from what I read it encountered memory issues which may be out of my scope and Martin will have to look at this, besides that, I read that you have integrated graphics and a quite old CPU, if you are just hosting a server on your laptop then it should work {barely} but if you want to play on the same device you most likely will run into some problems as this would be demanding for a vanilla server let alone a ntm modpack server. Best I can suggest is increasing dedicated ram and hoping for the best. I will try to read it through again tomorrow

**Comment by JulekJulas** [comment]
Never mind I just noticed you are unable to increase dedicated ram, maybe update java?(if outdated) sometimes it helped in weird situations.

**Comment by likeproblem** [comment]
> Never mind I just noticed you are unable to increase dedicated ram, maybe update java?(if outdated) sometimes it helped in weird situations.

Uhm, I made it bigger by changing run.bat with setting -Xmx6G

**Comment by likeproblem** [comment]
It is fixed by today's update 0.0.19.1

**Comment by MartinTheDragon** [comment]
Duplicate of #37
