### ISSUE TITLE
When I use this mod together with other mods it crashes before the game opens.⁹

### ISSUE THREAD

**Issue by Abishark** [MartinTheDragon/Nuclear-Tech-Mod-Remake#42]
### Issue description

The mods I used were create, valkyrien skies and optifine, but because of this problem I can't play hbm with other mods without crashing.

### Steps to reproduce

I just open the game with many other mod and then crashes with error code:1

### Forge version

Forge 1.18.2 40.2.0

### Nuclear Tech version

0.0.19

### Other mods

Valkyrien skies 8-2.1.0-beta9
Eureka 1.1.0-beta5
Create 0.5.0.g
Flywheel 0.6.8
Optifine HD_UH7
Jei 1.0.2.1.1283

**Comment by MartinTheDragon** [comment]
Hi!
OptiFine is known to cause issues. Please play without OptiFine.
Mod compatibility isn't planned, since I haven't yet found any documentation on what OptiFine does nor how it expects other mods to behave.

**Comment by JulekJulas** [comment]
Rubidium with iris, oculus and create iris compatibility works great with VS, NTM and Create. I tested it with it alone and a huge modpack. It has less functions but it's way more optimised and it only breaks with soft voxels lite so far and not sure why. SEUS, Sildurs and similar work great.

**Comment by JulekJulas** [comment]
Actually remove iris I forgot that oculus is the forge fork of it
