### ISSUE TITLE
As soon as I connect to my server, it doesn't let me back in

### ISSUE THREAD

**Issue by rohanverma2007** [MartinTheDragon/Nuclear-Tech-Mod-Remake#45]
### Issue description

![image](https://user-images.githubusercontent.com/120854107/220358092-f0b21f3b-7c5a-41f8-90e6-2a1621a9eae7.png)
[latest.log](https://github.com/MartinTheDragon/Nuclear-Tech-Mod-Remake/files/10794245/latest.log)

I keep getting this error whenever trying to connect to my server.

### Steps to reproduce

1. Use dedicated server with other mods
2. Crash client and never allowed to connect to server for some strange reason.

### Forge version

1.18.2 40.2.1

### Nuclear Tech version

Manually compiled

### Other mods

![Screenshot_13](https://user-images.githubusercontent.com/120854107/220368309-44d5d936-e424-44ee-b281-41725596ea52.png)
![Screenshot_11](https://user-images.githubusercontent.com/120854107/220368314-4aa47e58-9887-4b21-beed-bb4c10741a65.png)
![Screenshot_12](https://user-images.githubusercontent.com/120854107/220368318-34fe2b1a-8649-4934-a7df-b63ab9371bcb.png)

Entire Mods List

### (Crash) Log

[latest.log](https://github.com/MartinTheDragon/Nuclear-Tech-Mod-Remake/files/10794245/latest.log)

**Comment by rohanverma2007** [comment]
im using the snapshot version of nuclear tech

**Comment by Officialy** [comment]
Could you send the debug log too, along with the server log? 
If you don't have a debug log, just the server log will do for now

**Comment by TechSupportRed** [comment]
Sure one moment.

**Comment by rohanverma2007** [comment]
[debug.log](https://github.com/MartinTheDragon/Nuclear-Tech-Mod-Remake/files/10795732/debug.log)
[latest.log](https://github.com/MartinTheDragon/Nuclear-Tech-Mod-Remake/files/10795733/latest.log)

**Comment by MartinTheDragon** [comment]
Hi!
Can you please try resending the server log? It appears as if the file is empty.

**Comment by JulekJulas** [comment]
My current server modpack does this, I fix it by joining a single player world and then rejoining, it works most of the time. If it fixes it for you it's not NTM's fault.

**Comment by rohanverma2007** [comment]
[debug.log](https://github.com/MartinTheDragon/Nuclear-Tech-Mod-Remake/files/10803988/debug.log)
[latest.log](https://github.com/MartinTheDragon/Nuclear-Tech-Mod-Remake/files/10803989/latest.log)

**Comment by rohanverma2007** [comment]
I think this server log works, I am going to try JulekJulas method first

**Comment by MartinTheDragon** [comment]
Well, the log seems to not contain any information on what causes your issue. It only implies that it must be a packet handler that runs on login. I looked through all the server-bound packets in NTM and couldn't find any of them referencing the client-only `Minecraft` class.

**Comment by rohanverma2007** [comment]
JulekJulas method didn't work, however I am going to try deleting mods one at a time

**Comment by JulekJulas** [comment]
It might be Hex casting then

**Comment by rohanverma2007** [comment]
Still experiencing this issue, however it let me connect to the server this time for like 10 seconds
![image](https://user-images.githubusercontent.com/120854107/220711577-554eedd9-0e51-428b-a6b4-fd525fc8ce06.png)

**Comment by MartinTheDragon** [comment]
Looks like the hazard system network packet filter also got injected into the server-side connection, which enqueues a task onto the `Minecraft` class when it detects a client-bound entity data update packet.
Thanks for reporting!
