### ISSUE TITLE
Curseforge problem (i cant upload ur mod)

### ISSUE THREAD

**Issue by anotherRandomPersonlol** [MartinTheDragon/Nuclear-Tech-Mod-Remake#49]
Curseforge is a **f--king** b--ch and wont accept me getting this into curseforge. I need you to as yourself put this in curseforge beacuse i want to put it in my server and aternos is too scared to let me use your own mod into my pc to aternos beacuse "YoU pUt a MoD tHaT kEePs OuR sErVeRs OnLiNe" bro you can literally run a wurst client and turn on auto reconnect, its that simple to keep a server online. but the main part is that you need to put your own mod into curseforge.

**Comment by 70000hp** [comment]
this is peak copypasta material thank you
