### ISSUE TITLE
shift+right click on detonator doesnt work

### ISSUE THREAD

**Issue by brambora69123** [MartinTheDragon/Nuclear-Tech-Mod-Remake#6]
**Describe the bug**
When I try to set the position of detonator, it does not work.

**To Reproduce**
1. Get the detonator
2. Shift+Right click on a place where u want it to go
3. Nothing happens.

**Expected behavior**
Successful set of position

**Software and mod environment info (please complete the following information):**
 - Mod Version: 0.0.11.0
 - Other mods installed: 
![image](https://user-images.githubusercontent.com/74984053/160135129-a1179a93-2f9a-441b-819e-ecdaa4761f5b.png)
 - Forge version: 1.18.1-39.1.2

**Comment by MartinTheDragon** [comment]
Hi there!

Setting the detonator's position only works on blocks that implement the `IgnitableExplosive` interface (which may at a later point be part of a public API). This means you need to set the position on a block that is compatible (e.g. Fat Man).

Have fun and keep on bug hunting!

**Comment by brambora69123** [comment]
I was doing it wrong lol

**Comment by MartinTheDragon** [comment]
Oh, by the way: OptiFine may cause problems with the mod's rendering, in case you're having issues like weird models.

**Comment by MartinTheDragon** [comment]
Please remove the angle brackets in the title next time, because it apparently messes with our webhook lol
