### ISSUE TITLE
Satellite Dish?

### ISSUE THREAD

**Issue by IamcomingfromJUPITER** [MartinTheDragon/Nuclear-Tech-Mod-Remake#61]
Please add the Satellite Dish decoration block.

**Comment by JulekJulas** [comment]
Please read the FAQ channel on discord before you make github issues.
From the channel:
Q: Will you add X feature from 1.7/1.12?
A: My aim is to get all of the things that are progression-related from 1.7 ported first, then all the other things like utilities, cosmetics, deco and meme references. After that, I can look at the specifics of the 1.12 version.
