### ISSUE TITLE
can i download

### ISSUE THREAD

**Issue by Dr-krumpet** [MartinTheDragon/Nuclear-Tech-Mod-Remake#8]
ok so your mod sounds Really good but how do i download it

**Comment by MartinTheDragon** [comment]
Hi!
You have to go to the [releases page](https://github.com/MartinTheDragon/Nuclear-Tech-Mod-Remake/releases), and then on the latest release scroll down until you see "Assets". Then you click on the little arrow next to that, and voila, you'll see the mod jar.

PS: READMEs are called that way for a reason ;)
